### ISSUE TITLE
builtins.RuntimeError: No active exception to reraise

### ISSUE THREAD

**Issue by alallier** [twitterdev/sample-python-autoreply#3]
I recieve this error when running the example code I was wondering if you could help me out. It receives the tweet and generates the reply text but errors out after that.

Output from terminal
```
[evaluate twitter.py]
{"friends":[77093860]}


{"created_at":"Sat Aug 15 14:25:47 +0000 2015","id":632558809265897472,"id_str":"632558809265897472","text":"@WestmoStoplight Test9","source":"\u003ca href=\"http:\/\/twitter.com\" rel=\"nofollow\"\u003eTwitter Web Client\u003c\/a\u003e","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":3413802454,"in_reply_to_user_id_str":"3413802454","in_reply_to_screen_name":"WestmoStoplight","user":{"id":229876754,"id_str":"229876754","name":"Alex Lallier","screen_name":"Alallier19","location":"","url":"http:\/\/www.youtube.com\/planestrainsautos","description":"Just a relaxed guy that loves to hang out, drive snowmobiles, and work on computers. You call me i'll be there.","protected":false,"verified":false,"followers_count":55,"friends_count":68,"listed_count":0,"favourites_count":0,"statuses_count":39,"created_at":"Thu Dec 23 15:40:06 +0000 2010","utc_offset":-18000,"time_zone":"Central Time (US & Canada)","geo_enabled":false,"lang":"en","contributors_enabled":false,"is_translator":false,"profile_background_color":"C0DEED","profile_background_image_url":"http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_image_url_https":"https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png","profile_background_tile":false,"profile_link_color":"0084B4","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/440613182478876673\/2aPM2tx-_normal.jpeg","profile_image_url_https":"https:\/\/pbs.twimg.com\/profile_images\/440613182478876673\/2aPM2tx-_normal.jpeg","default_profile":true,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":null,"contributors":null,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[],"trends":[],"urls":[],"user_mentions":[{"screen_name":"WestmoStoplight","name":"Westmo Pi","id":3413802454,"id_str":"3413802454","indices":[0,16]}],"symbols":[]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"filter_level":"low","lang":"en","timestamp_ms":"1439648747160"}

Tweet ID: 632558809265897472
From: Alallier19
Tweet Text: @WestmoStoplight Test9
Reply Text: @Alallier19 How do you feel when you say that?
Traceback (most recent call last):
  File "C:\Program Files (x86)\Wing IDE 101 5.1\src\debug\tserver\_sandbox.py", line 66, in <module>
  File "c:\Python34\Lib\site-packages\tweepy\streaming.py", line 379, in userstream
    self._start(async)
  File "c:\Python34\Lib\site-packages\tweepy\streaming.py", line 346, in _start
    self._run()
  File "c:\Python34\Lib\site-packages\tweepy\streaming.py", line 286, in _run
    raise
builtins.RuntimeError: No active exception to reraise
```

**Comment by alallier** [comment]
Update: Seems to be an issue with tweepy itself https://github.com/tweepy/tweepy/issues/570
